services:
  catalogdb:
    image: postgres:18.0

  basketdb:
    image: postgres:18.0

  adminer:
    image: adminer

  distributedcache:
    image: redis:8.2.3-alpine3.22

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/BasketAPI/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:

