services:
  catalogdb:
    image: postgres:18.0
  adminer:
    image: adminer

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

volumes:
  postgres_catalog:
